//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Ecommerce;

[assembly: RegisterDocumentType(Transformations.CLASS_NAME, typeof(Transformations))]

namespace CMS.DocumentEngine.Types.Ecommerce
{
	/// <summary>
	/// Represents a content item of type Transformations.
	/// </summary>
	public partial class Transformations : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Ecommerce.Transformations";


		/// <summary>
		/// The instance of the class that provides extended API for working with Transformations fields.
		/// </summary>
		private readonly TransformationsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Gets an object that provides extended API for working with Transformations fields.
		/// </summary>
		[RegisterProperty]
		public TransformationsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Transformations fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class TransformationsFields : AbstractHierarchicalObject<TransformationsFields>
		{
			/// <summary>
			/// The content item of type Transformations that is a target of the extended API.
			/// </summary>
			private readonly Transformations mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="TransformationsFields" /> class with the specified content item of type Transformations.
			/// </summary>
			/// <param name="instance">The content item of type Transformations that is a target of the extended API.</param>
			public TransformationsFields(Transformations instance)
			{
				mInstance = instance;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Transformations" /> class.
		/// </summary>
		public Transformations() : base(CLASS_NAME)
		{
			mFields = new TransformationsFields(this);
		}

		#endregion
	}
}